<?php
/**
 * Created by PhpStorm.
 * User: claudio
 * Date: 05/09/2016
 * Time: 11:28
 */

namespace Auth\Google;


class Google extends \Hybrid_Auth {

    /**
     * @param array $config
     */
    public function __construct($config)
    {
        parent::__construct($config); // TODO: Change the autogenerated stub
    }


} 