<form method="POST" name="Traduction" id="Manager" enctype="multipart&#x2F;form-data" class="form-horizontal" role="form" action="action-form-do-formulario">
    <fieldset>
        <legend>FORMULARI DE MANUTENÇÃO</legend>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
                <fieldset>
                    <legend>GERAL</legend>
                    #id#
                    #asset_id#
                    #codigo#
                    #empresa#

                    <div> <label class="control-label" for="title">
                            {{title}}
                        </label><div class="valid&#x20;title">
                            #title#
                        </div>

                    </div>

                    <div> <label class="control-label" for="description">
                            {{description}}
                        </label><div class="valid&#x20;description">
                            #description#
                        </div>

                    </div>
                    <div> <label class="control-label" for="dica_tela">
                            {{dica_tela}}
                        </label><div class="valid&#x20;dica_tela">
                            #dica_tela#
                        </div>

                    </div>
                    <div> <label class="control-label" for="placeholder">
                            {{placeholder}}
                        </label><div class="valid&#x20;placeholder">
                            #placeholder#
                        </div>

                    </div>

                    #security#

                    <hr>
                    <button type="submit" name="save" class="btn&#x20;btn-primary" value="">SALVAR</button>
                    <button type="submit" disabled name="save-copy" id="save-copy" class="btn&#x20; btn-warning disabled" value="">COPIAR</button>
                    #btn-voltar#
                    <div class="clearfix"></div>
                </fieldset>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <fieldset>
                    <legend>FORMULARI DE ADICIONAL</legend>
                    <div class="row">
                        <div class="col-md-12">
                            <div> <label class="control-label" for="access">
                                    {{access}}
                                </label><div class="valid&#x20;access">
                                    #access#
                                </div>
                            </div>
                            <div> <label class="control-label" for="state">
                                    {{state}}
                                </label><div class="valid&#x20;state">
                                    #state#
                                </div>
                            </div>
                            <div> <label class="control-label" for="created">
                                    {{created}}
                                </label><div class="valid&#x20;created">
                                    #created#
                                </div>

                            </div>
                            #modified#
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="clearfix"></div>
    </fieldset>
</form>
