<form method="POST" name="Users" id="Manager" enctype="multipart&#x2F;form-data" class="form-horizontal" role="form" action="action-form-do-formulario">
    <fieldset>
        <legend>FORMULARI DE MANUTENÇÃO</legend>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
                <fieldset>
                    <legend>GERAL</legend>
                    #id#
                   <div class=""> <label class="control-label" for="title">
                            {{title}}
                        </label><div class="valid&#x20;title">
                            #title#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="cnpj">
                            {{cnpj}}
                        </label><div class="valid&#x20;cnpj">
                            #cnpj#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="email">
                            {{email}}
                        </label><div class="valid&#x20;email">
                            #email#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="phone">
                            {{phone}}
                        </label><div class="valid&#x20;phone">
                            #phone#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="role_id">
                            {{role_id}}
                        </label><div class="valid&#x20;role_id">
                            #role_id#
                        </div>

                    </div>
                    <div class=""> <label class="control-label" for="description">
                            {{description}}
                        </label><div class="valid&#x20;description">
                            #description#
                        </div>

                    </div>
                    #security#


                    <hr>
                    <button type="submit" name="save" class="btn&#x20;btn-primary" value="">SALVAR</button>
                    #btn-voltar#

                    <div class="clearfix"></div>
                </fieldset>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <fieldset>
                    <legend>FORMULARI DE ADICIONAL</legend>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="">     <div class="img-add images"><label class="control-label" for="images">
                                        {{images}}
                                    </label>
                                    #imagePriview#
                                </div>
                                <div class="valid&#x20;images">
                                    #images#
                                </div>

                                <p class="help-block">Max. 32MB</p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="col-md-12">
                            <div class=""> <label class="control-label" for="access">
                                    {{access}}
                                </label><div class="valid&#x20;access">
                                    #access#
                                </div>
                            </div>
                            <div class=""> <label class="control-label" for="state">
                                    {{state}}
                                </label><div class="valid&#x20;state">
                                    #state#
                                </div>
                            </div>
                            <div class=""> <label class="control-label" for="created">
                                    {{created}}
                                </label><div class="valid&#x20;created">
                                    #created#
                                </div>

                            </div>
                            #modified#
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="clearfix"></div>
    </fieldset>
</form>
