        <div class="form-group  has-feedback">
            #security#     #email#
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group  has-feedback">
            #password#
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="checkbox-box">
                <div class="checkbox icheck">
                    <label>
                        #rememberme# Lembre-me
                    </label>
                </div>
            </div><!-- /.col -->
            <div class="btn-logar-box">
                #logar#
            </div><!-- /.col -->
        </div>

