#security#
#modified#
#id#
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
        <fieldset>
            <legend>GERAL</legend>
            #id#
            <div class="form-group  has-feedback">
                #title#
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #email#
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>

            <div class="form-group  has-feedback">
                #phone#
                <span class="glyphicon glyphicon-phone form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #cnpj#
                <span class="glyphicon glyphicon-ok form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #gender#
            </div>
            <div class="form-group  has-feedback">
                #age#
                <span class="glyphicon glyphicon-ok form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #birthDay#
                <span class="glyphicon glyphicon-ok form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #birthMonth#
                <span class="glyphicon glyphicon-ok form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #cnpj#
                <span class="glyphicon glyphicon-ok form-control-feedback"></span>
            </div>

            <div class="form-group  has-feedback">
                #description#
                <span class="glyphicon glyphicon-list form-control-feedback"></span>
            </div>
            #security#
            <hr>
            <div class="row">
                <div class="col-xs-12">
                    #save#
                </div><!-- /.col -->
            </div>
           <div class="clearfix"></div>
        </fieldset>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <fieldset>
            <legend>FORMULARI DE ADICIONAL</legend>
            <div class="row">

                <div class="col-md-12">
                    <div>     <div class="img-add images"><label class="control-label" for="images">
                                {{images}}
                            </label>
                            #imagePreview#
                        </div>
                        <div class="valid&#x20;images">
                            #images#
                        </div>
                        <input type="file" class="atachament" id="atachament" name="atachament">
                        <p class="help-block">Max. 32MB</p>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
        </fieldset>
    </div>
</div>

