
        <div class="form-group  has-feedback">
            #title#
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>

        <div class="form-group  has-feedback">
            #email#
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>

        <div class="form-group  has-feedback">
            #phone#
            <span class="glyphicon glyphicon-phone form-control-feedback"></span>
        </div>

        <div class="form-group  has-feedback">
            #password#
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>

        <div class="form-group  has-feedback">
            #usr_password_confirm#
            <span class="glyphicon glyphicon-ok form-control-feedback"></span>
        </div>

        <div class="form-group  has-feedback">
            #description#
            <span class="glyphicon glyphicon-list form-control-feedback"></span>
        </div>
        <div class="form-group  has-feedback">
            #captcha#

        </div>
        <div class="row">
            <div class="col-xs-12">
                #save#
            </div><!-- /.col -->
        </div>
         #security#
