<form method="POST" name="Produtos" id="Manager" enctype="multipart&#x2F;form-data" class="form-horizontal" role="form" action="action-form-do-formulario">
<fieldset>
    <legend>FORMULARI DE MANUTENÇÃO</legend>
    <div class="row">
    	<div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
            <fieldset>
                <legend>GERAL</legend>
                #id#
#asset_id#
#codigo#
#empresa#
<div> <label class="control-label" for="tipo">
{{tipo}}
</label><div class="valid&#x20;tipo">
#tipo#
</div>

</div>
<div> <label class="control-label" for="title">
{{title}}
</label><div class="valid&#x20;title">
#title#
</div>

</div>
<div> <label class="control-label" for="subtitle">
{{subtitle}}
</label><div class="valid&#x20;subtitle">
#subtitle#
</div>

</div>
<div> <label class="control-label" for="catid">
{{catid}}
</label><div class="valid&#x20;catid">
#catid#
</div>

</div>
<div> <label class="control-label" for="marca">
{{marca}}
</label><div class="valid&#x20;marca">
#marca#
</div>

</div>
<div> <label class="control-label" for="unidade">
{{unidade}}
</label><div class="valid&#x20;unidade">
#unidade#
</div>

</div>
<div> <label class="control-label" for="pago">
{{pago}}
</label><div class="valid&#x20;pago">
#pago#
</div>

</div>
<div> <label class="control-label" for="lucro">
{{lucro}}
</label><div class="valid&#x20;lucro">
#lucro#
</div>

</div>
<div> <label class="control-label" for="valor">
{{valor}}
</label><div class="valid&#x20;valor">
#valor#
</div>

</div>
<div> <label class="control-label" for="peso">
{{peso}}
</label><div class="valid&#x20;peso">
#peso#
</div>

</div>
<div> <label class="control-label" for="altura">
{{altura}}
</label><div class="valid&#x20;altura">
#altura#
</div>

</div>
<div> <label class="control-label" for="lagura">
{{lagura}}
</label><div class="valid&#x20;lagura">
#lagura#
</div>

</div>
<div> <label class="control-label" for="estoque">
{{estoque}}
</label><div class="valid&#x20;estoque">
#estoque#
</div>

</div>
<div> <label class="control-label" for="minimo">
{{minimo}}
</label><div class="valid&#x20;minimo">
#minimo#
</div>

</div>
<div> <label class="control-label" for="description">
{{description}}
</label><div class="valid&#x20;description">
#description#
</div>
 
</div>
#security#

                <hr>
                <button type="submit" name="save" class="btn&#x20;btn-primary" value="">SALVAR</button>
#btn-voltar#
                <div class="clearfix"></div>
            </fieldset>
    	</div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <fieldset>
                <legend>FORMULARI DE ADICIONAL</legend>
               <div class="row">
                   <div class="col-md-12">
                       <div>     <div class="img-add images"><label class="control-label" for="images">
{{images}}
</label>
         #imagePriview#
     </div>
    <div class="valid&#x20;images">
#images#
</div>
     <input type="file" class="atachament" id="atachament" name="atachament">
     <p class="help-block">Max. 32MB</p>
</div>
                       <div class="clearfix"></div>
                   </div>
                   <div class="col-md-12">
                      <div> <label class="control-label" for="access">
{{access}}
</label><div class="valid&#x20;access">
#access#
</div>
 </div>
<div> <label class="control-label" for="state">
{{state}}
</label><div class="valid&#x20;state">
#state#
</div>
 </div>
<div> <label class="control-label" for="created">
{{created}}
</label><div class="valid&#x20;created">
#created#
</div>

</div>
#modified#
                       <div class="clearfix"></div>
                   </div>
               </div>
            </fieldset>
        </div>
    </div>
    <div class="clearfix"></div>
</fieldset>
</form>
