<?php
/**
 * @license © 2005 - 2016 by Zend Technologies Ltd. All rights reserved.
 */


namespace Pg\Model\Pgassinaturas;

use Base\Model\AbstractModel;
use Base\Model\Check;
use Zend\Db\TableGateway\TableGateway;
use Base\Model\AbstractRepository;

/**
 * SIGA-Smart
 *
 * Esta class foi gerada via Zend\Code\Generator.
 */
class PgassinaturasRepository extends AbstractRepository
{

    /**
     * __construct Factory Model
     *
     * @param TableGateway $tableGateway
     * @return \Pg\Model\Pgassinaturas\PgassinaturasRepository
     */
    public function __construct(TableGateway $tableGateway)
    {
        // Configurações iniciais do Factory Repository
        $this->tableGateway=$tableGateway;
    }

    public function insert(AbstractModel $model)
    {
        $model->setTitle(Check::Name($model->getPreApprovalName()));
        return parent::insert($model); // TODO: Change the autogenerated stub
    }

    public function update(AbstractModel $model, $where = null)
    {
        $model->setTitle(Check::Name($model->getPreApprovalName()));
        return parent::update($model, $where); // TODO: Change the autogenerated stub
    }


}