<div class="box login-box">
    <div class="main-login-header">
        <a href="<?php echo $this->url('admin') ?>"></a>
    </div><!-- /.login-logo -->
    <div class="main-login-box login-box-body">
         <p class="alert alert-info">Digite Seu Email Para Enviarmos Uma Nova Senha</p>
         <?php $partial=$this->partial("/auth/auth/tpl/forgothen-password");
         $form->setAttribute('action',$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'forgothen-password']));?>
        <?=$this->UserIdentity()->getForm($partial,$form);?>
          <p class="p-separator">
              <a href="<?php echo $this->url("home") ?>">&larrhk; Voltar para Site!</a> &nbsp;&nbsp;&nbsp;
              <a href="<?=$this->url("auth");?>"><?php echo $this->translate('&larrhk;  Voltar P/ Login'); ?></a>
              &nbsp;&nbsp;&nbsp;
            <a href="<?=$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'register']);?>"><?php echo $this->translate('&larrhk; Register'); ?></a>
            <br>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->
