<style>
    .login-box a {
        color: #555;
        text-decoration: none;
        font-size: 0.8em;
        margin-top: 10px;
        text-transform: uppercase;
        font-weight: 300; }

    .login-box a:hover {
        text-decoration: underline; }
</style>
<div class="box login-box">
    <div class="main-login-header">
        <a href="<?php echo $this->url('admin') ?>"></a>
    </div><!-- /.login-logo -->
    <div class="main-login-box login-box-body">
        <?php echo $this->messages(); ?>
        <?php $partial=$this->partial("/auth/auth/tpl/profile");
        $form->setAttribute('action',$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'update-profile']));?>
        <?=$this->UserIdentity()->getForm($partial,$form);?>
        <hr>
        <p class="p-separator">
            <a  href="<?php echo $this->url("home") ?>">&larrhk; Voltar para Site!</a> &nbsp;&nbsp;&nbsp;
            <a  href="<?=$this->url("admin");?>"><?php echo $this->translate('Voltar Para Administração &#8618;'); ?></a>
        </p>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->