<div class="box login-box">
    <div class="main-login-header">
        <a href="<?php echo $this->url('admin') ?>"></a>
    </div><!-- /.login-logo -->
    <div class="main-login-box login-box-body">
         <?php $partial=$this->partial("/auth/auth/tpl/update-password");
        $form->setAttribute('action',$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'update-password']));?>
        <?=$this->UserIdentity()->getForm($partial,$form);?>
        <div class="col-xs-12 col-md-6 col-md-offset-3 col-xs-offset-0">
        <p class="p-separator">
            <a  href="<?php echo $this->url("home") ?>">&larrhk; Voltar para Site!</a> &nbsp;&nbsp;&nbsp;
            <a  href="<?=$this->url("admin");?>"><?php echo $this->translate('Voltar Para Administração &#8618;'); ?></a>
            <br>
            </p></div>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->
