<?php
return array(
    'service_manager' => array(
        'factories' => array(
            'Auth\\Model\\Users\\Users' => 'Auth\\Model\\Users\\Factory\\UsersFactory',
            'Auth\\Model\\Users\\UsersRepository' => 'Auth\\Model\\Users\\Factory\\UsersRepositoryFactory',
            'Auth\\Form\\UsersForm' => 'Auth\\Form\\Factory\\UsersFormFactory',
            'Auth\\Form\\UsersFilter' => 'Auth\\Form\\Factory\\UsersFilterFactory',
            'Admin\\Model\\Configuracao\\Configuracao' => 'Admin\\Model\\Configuracao\\Factory\\ConfiguracaoFactory',
            'Admin\\Model\\Configuracao\\ConfiguracaoRepository' => 'Admin\\Model\\Configuracao\\Factory\\ConfiguracaoRepositoryFactory',
            'Admin\\Form\\ConfiguracaoForm' => 'Admin\\Form\\Factory\\ConfiguracaoFormFactory',
            'Admin\\Form\\ConfiguracaoFilter' => 'Admin\\Form\\Factory\\ConfiguracaoFilterFactory',
            'Auth\\Model\\Privileges\\Privileges' => 'Auth\\Model\\Privileges\\Factory\\PrivilegesFactory',
            'Auth\\Model\\Privileges\\PrivilegesRepository' => 'Auth\\Model\\Privileges\\Factory\\PrivilegesRepositoryFactory',
            'Auth\\Form\\PrivilegesForm' => 'Auth\\Form\\Factory\\PrivilegesFormFactory',
            'Auth\\Form\\PrivilegesFilter' => 'Auth\\Form\\Factory\\PrivilegesFilterFactory',
            'Auth\\Model\\Resources\\Resources' => 'Auth\\Model\\Resources\\Factory\\ResourcesFactory',
            'Auth\\Model\\Resources\\ResourcesRepository' => 'Auth\\Model\\Resources\\Factory\\ResourcesRepositoryFactory',
            'Auth\\Form\\ResourcesForm' => 'Auth\\Form\\Factory\\ResourcesFormFactory',
            'Auth\\Form\\ResourcesFilter' => 'Auth\\Form\\Factory\\ResourcesFilterFactory',
            'Auth\\Model\\Roles\\Roles' => 'Auth\\Model\\Roles\\Factory\\RolesFactory',
            'Auth\\Model\\Roles\\RolesRepository' => 'Auth\\Model\\Roles\\Factory\\RolesRepositoryFactory',
            'Auth\\Form\\RolesForm' => 'Auth\\Form\\Factory\\RolesFormFactory',
            'Auth\\Form\\RolesFilter' => 'Auth\\Form\\Factory\\RolesFilterFactory',
            'Auth\\Model\\RedeSociais\\RedeSociais' => 'Auth\\Model\\RedeSociais\\Factory\\RedeSociaisFactory',
            'Auth\\Model\\RedeSociais\\RedeSociaisRepository' => 'Auth\\Model\\RedeSociais\\Factory\\RedeSociaisRepositoryFactory',
            'Auth\\Form\\RedeSociaisForm' => 'Auth\\Form\\Factory\\RedeSociaisFormFactory',
            'Auth\\Form\\RedeSociaisFilter' => 'Auth\\Form\\Factory\\RedeSociaisFilterFactory',
            'Admin\\Model\\PagSeguro\\PagSeguro' => 'Admin\\Model\\PagSeguro\\Factory\\PagSeguroFactory',
            'Admin\\Model\\PagSeguro\\PagSeguroRepository' => 'Admin\\Model\\PagSeguro\\Factory\\PagSeguroRepositoryFactory',
            'Admin\\Form\\PagSeguroForm' => 'Admin\\Form\\Factory\\PagSeguroFormFactory',
            'Admin\\Form\\PagSeguroFilter' => 'Admin\\Form\\Factory\\PagSeguroFilterFactory',
            'Pg\\Model\\Pgassinaturas\\Pgassinaturas' => 'Pg\\Model\\Pgassinaturas\\Factory\\PgassinaturasFactory',
            'Pg\\Model\\Pgassinaturas\\PgassinaturasRepository' => 'Pg\\Model\\Pgassinaturas\\Factory\\PgassinaturasRepositoryFactory',
            'Pg\\Form\\PgassinaturasForm' => 'Pg\\Form\\Factory\\PgassinaturasFormFactory',
            'Pg\\Form\\PgassinaturasFilter' => 'Pg\\Form\\Factory\\PgassinaturasFilterFactory',
            'Ecommerce\\Model\\Produtos\\Produtos' => 'Ecommerce\\Model\\Produtos\\Factory\\ProdutosFactory',
            'Ecommerce\\Model\\Produtos\\ProdutosRepository' => 'Ecommerce\\Model\\Produtos\\Factory\\ProdutosRepositoryFactory',
            'Ecommerce\\Form\\ProdutosForm' => 'Ecommerce\\Form\\Factory\\ProdutosFormFactory',
            'Ecommerce\\Form\\ProdutosFilter' => 'Ecommerce\\Form\\Factory\\ProdutosFilterFactory',
            'Admin\\Model\\Traduction\\Traduction' => 'Admin\\Model\\Traduction\\Factory\\TraductionFactory',
            'Admin\\Model\\Traduction\\TraductionRepository' => 'Admin\\Model\\Traduction\\Factory\\TraductionRepositoryFactory',
            'Admin\\Form\\TraductionForm' => 'Admin\\Form\\Factory\\TraductionFormFactory',
            'Admin\\Form\\TraductionFilter' => 'Admin\\Form\\Factory\\TraductionFilterFactory',
            'Ecommerce\\Model\\Categorias\\Categorias' => 'Ecommerce\\Model\\Categorias\\Factory\\CategoriasFactory',
            'Ecommerce\\Model\\Categorias\\CategoriasRepository' => 'Ecommerce\\Model\\Categorias\\Factory\\CategoriasRepositoryFactory',
            'Ecommerce\\Form\\CategoriasForm' => 'Ecommerce\\Form\\Factory\\CategoriasFormFactory',
            'Ecommerce\\Form\\CategoriasFilter' => 'Ecommerce\\Form\\Factory\\CategoriasFilterFactory',
            'Ecommerce\\Model\\Marcas\\Marcas' => 'Ecommerce\\Model\\Marcas\\Factory\\MarcasFactory',
            'Ecommerce\\Model\\Marcas\\MarcasRepository' => 'Ecommerce\\Model\\Marcas\\Factory\\MarcasRepositoryFactory',
            'Ecommerce\\Form\\MarcasForm' => 'Ecommerce\\Form\\Factory\\MarcasFormFactory',
            'Ecommerce\\Form\\MarcasFilter' => 'Ecommerce\\Form\\Factory\\MarcasFilterFactory',
        ),
    ),
    'controllers' => array(
        'factories' => array(
            'Auth\\Controller\\Users' => 'Auth\\Controller\\Factory\\UsersControllerFactory',
            'Admin\\Controller\\Configuracao' => 'Admin\\Controller\\Factory\\ConfiguracaoControllerFactory',
            'Auth\\Controller\\Privileges' => 'Auth\\Controller\\Factory\\PrivilegesControllerFactory',
            'Auth\\Controller\\Resources' => 'Auth\\Controller\\Factory\\ResourcesControllerFactory',
            'Auth\\Controller\\Roles' => 'Auth\\Controller\\Factory\\RolesControllerFactory',
            'Auth\\Controller\\RedeSociais' => 'Auth\\Controller\\Factory\\RedeSociaisControllerFactory',
            'Admin\\Controller\\PagSeguro' => 'Admin\\Controller\\Factory\\PagSeguroControllerFactory',
            'Pg\\Controller\\Pgassinaturas' => 'Pg\\Controller\\Factory\\PgassinaturasControllerFactory',
            'Ecommerce\\Controller\\Produtos' => 'Ecommerce\\Controller\\Factory\\ProdutosControllerFactory',
            'Admin\\Controller\\Traduction' => 'Admin\\Controller\\Factory\\TraductionControllerFactory',
            'Ecommerce\\Controller\\Categorias' => 'Ecommerce\\Controller\\Factory\\CategoriasControllerFactory',
            'Ecommerce\\Controller\\Marcas' => 'Ecommerce\\Controller\\Factory\\MarcasControllerFactory',
        ),
    ),
);
