<?php
return array(
    'Admin' => array(
        'label' => 'Administrativo',
        'class' => 'treeview',
        'action' => '#',
        'icone' => '',
        'title' => 'Administrativo',
        'pages' => array(
            0 => array(
                'label' => 'CONIGURAçõES',
                'route' => 'admin/default',
                'controller' => 'configuracao',
                'resource' => 'Admin\\Controller\\Configuracao',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'ok',
            ),
            1 => array(
                'label' => 'TRADUTOR',
                'route' => 'admin/default',
                'controller' => 'traduction',
                'resource' => 'Admin\\Controller\\Traduction',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'bs_traduction',
            ),
        ),
    ),
    'Auth' => array(
        'label' => 'Controle de Acesso',
        'class' => 'treeview',
        'action' => '#',
        'icone' => '',
        'title' => 'Controle de Acesso',
        'pages' => array(
            0 => array(
                'label' => 'USUARIOS',
                'route' => 'auth/default',
                'controller' => 'users',
                'resource' => 'Auth\\Controller\\Users',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'ok',
            ),
            1 => array(
                'label' => 'PRIVILéGIOS',
                'route' => 'auth/default',
                'controller' => 'privileges',
                'resource' => 'Auth\\Controller\\Privileges',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'ok',
            ),
            2 => array(
                'label' => 'RESOURCES',
                'route' => 'auth/default',
                'controller' => 'resources',
                'resource' => 'Auth\\Controller\\Resources',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'resources',
            ),
            3 => array(
                'label' => 'ROLES',
                'route' => 'auth/default',
                'controller' => 'roles',
                'resource' => 'Auth\\Controller\\Roles',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'ok',
            ),
            4 => array(
                'label' => 'REDE SOCIAIS',
                'route' => 'auth/default',
                'controller' => 'redesociais',
                'resource' => 'Auth\\Controller\\Redesociais',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => 'icon-android icon-md icon-color2',
                'title' => 'configura??o das? redes sociais para acessar o sistema',
            ),
        ),
    ),
    'Make' => array(
        'label' => 'Construtor de Modulos',
        'class' => 'treeview',
        'action' => '#',
        'icone' => '',
        'title' => 'Construtor de Modulos',
        'pages' => array(
            0 => array(
                'label' => 'MAKE',
                'route' => 'make/default',
                'controller' => 'makes',
                'resource' => 'Make\\Controller\\Makes',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'modulo para construir outros modulos',
            ),
        ),
    ),
    'Pag Seguro' => array(
        'label' => 'PAG SEGURO',
        'class' => 'treeview',
        'action' => '#',
        'icone' => '',
        'title' => 'PAG SEGURO',
        'pages' => array(
            0 => array(
                'label' => 'PAG SEGURO',
                'route' => 'pagseguro/default',
                'controller' => 'pagseguro',
                'resource' => 'Admin\\Controller\\PagSeguro',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'ok',
            ),
            1 => array(
                'label' => 'PG ASSINATURAS',
                'route' => 'pagseguro/default',
                'controller' => 'pgassinaturas',
                'resource' => 'Pg\\Controller\\Pgassinaturas',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'pg assinaturas',
            ),
        ),
    ),
    'Ecommerce' => array(
        'label' => 'E-commerce',
        'class' => 'treeview',
        'action' => '#',
        'icone' => '',
        'title' => 'E-commerce',
        'pages' => array(
            0 => array(
                'label' => 'PRODUTOS',
                'route' => 'ecommerce/default',
                'controller' => 'produtos',
                'resource' => 'Ecommerce\\Controller\\Produtos',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'controla os produtos',
            ),
            1 => array(
                'label' => 'CATEGORIAS',
                'route' => 'ecommerce/default',
                'controller' => 'categorias',
                'resource' => 'Ecommerce\\Controller\\Categorias',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'categorias',
            ),
            2 => array(
                'label' => 'MARCAS',
                'route' => 'ecommerce/default',
                'controller' => 'marcas',
                'resource' => 'Ecommerce\\Controller\\Marcas',
                'action' => 'index',
                'privilege' => 'index',
                'icone' => '',
                'title' => 'marcas',
            ),
        ),
    ),
);